package main

import (
	"encoding/binary"
	"net"
	"net/netip"
	"reflect"
	"strings"
	"testing"
	"time"

	"github.com/mdlayher/ndp"
	"github.com/vishvananda/netlink/nl"
	"golang.org/x/sys/unix"
)

// ndUserOptMsg builds an RTM_NEWNDUSEROPT payload like the kernel does in
// ndisc_ra_useropt(): struct nduseroptmsg, the ND options, then an
// NDUSEROPT_SRCADDR attribute (which parseNDUserOpt must skip). The kernel
// sends one option per message; multiple options are accepted defensively.
func ndUserOptMsg(ifindex int, icmpType uint8, opts ...[]byte) []byte {
	var optsLen int
	for _, o := range opts {
		optsLen += len(o)
	}
	b := make([]byte, sizeofNDUserOptMsg)
	b[0] = unix.AF_INET6
	nl.NativeEndian().PutUint16(b[2:4], uint16(optsLen))
	nl.NativeEndian().PutUint32(b[4:8], uint32(ifindex))
	b[8] = icmpType
	for _, o := range opts {
		b = append(b, o...)
	}
	// NDUSEROPT_SRCADDR rtattr: len 20, type 1, fe80::1
	attr := make([]byte, 4, 20)
	nl.NativeEndian().PutUint16(attr[0:2], 20)
	nl.NativeEndian().PutUint16(attr[2:4], 1)
	attr = append(attr, net.ParseIP("fe80::1")...)
	return append(b, attr...)
}

func rdnssOpt(lifetime uint32, servers ...string) []byte {
	o := make([]byte, 8, 8+16*len(servers))
	o[0] = 25 // RDNSS
	o[1] = uint8(1 + 2*len(servers))
	binary.BigEndian.PutUint32(o[4:8], lifetime)
	for _, s := range servers {
		o = append(o, net.ParseIP(s).To16()...)
	}
	return o
}

func TestParseNDUserOpt(t *testing.T) {
	for _, tt := range []struct {
		name        string
		msg         []byte
		wantIfindex int
		want        []ndp.Option
		wantErr     bool
	}{
		{
			name:        "RDNSS single server",
			msg:         ndUserOptMsg(2, icmpv6RouterAdvertisement, rdnssOpt(1800, "2001:db8::53")),
			wantIfindex: 2,
			want: []ndp.Option{
				&ndp.RecursiveDNSServer{Lifetime: 1800 * time.Second, Servers: addrs("2001:db8::53")},
			},
		},
		{
			name:        "RDNSS multiple servers and options",
			msg:         ndUserOptMsg(3, icmpv6RouterAdvertisement, rdnssOpt(0xffffffff, "2001:db8::1", "fe80::1"), rdnssOpt(0, "2001:db8::2")),
			wantIfindex: 3,
			want: []ndp.Option{
				&ndp.RecursiveDNSServer{Lifetime: ndp.Infinity, Servers: addrs("2001:db8::1", "fe80::1")},
				&ndp.RecursiveDNSServer{Lifetime: 0, Servers: addrs("2001:db8::2")},
			},
		},
		{
			name:        "not a router advertisement",
			msg:         ndUserOptMsg(2, 136, rdnssOpt(1800, "2001:db8::53")),
			wantIfindex: 2,
		},
		{
			name:    "too short",
			msg:     []byte{unix.AF_INET6, 0, 0},
			wantErr: true,
		},
		{
			name:    "options truncated",
			msg:     ndUserOptMsg(2, icmpv6RouterAdvertisement, rdnssOpt(1800, "2001:db8::53"))[:sizeofNDUserOptMsg+8],
			wantErr: true,
		},
		{
			name:    "RDNSS option without addresses",
			msg:     ndUserOptMsg(2, icmpv6RouterAdvertisement, []byte{25, 1, 0, 0, 0, 0, 0, 0}),
			wantErr: true,
		},
	} {
		t.Run(tt.name, func(t *testing.T) {
			ifindex, got, err := parseNDUserOpt(tt.msg)
			if gotErr := err != nil; gotErr != tt.wantErr {
				t.Fatalf("parseNDUserOpt: err = %v, wantErr = %v", err, tt.wantErr)
			}
			if tt.wantErr {
				return
			}
			if ifindex != tt.wantIfindex {
				t.Errorf("parseNDUserOpt: ifindex = %d, want %d", ifindex, tt.wantIfindex)
			}
			if !reflect.DeepEqual(got, tt.want) {
				t.Errorf("parseNDUserOpt = %+v, want %+v", got, tt.want)
			}
		})
	}
}

func nameservers(contents []byte) []string {
	var result []string
	for _, line := range strings.Split(string(contents), "\n") {
		if ns, ok := strings.CutPrefix(line, "nameserver "); ok {
			result = append(result, ns)
		}
	}
	return result
}

func render(s *resolvState, now time.Time) []byte {
	s.mu.Lock()
	defer s.mu.Unlock()
	contents, _, _ := s.render(now)
	return contents
}

func ipv4s(s ...string) []net.IP {
	var result []net.IP
	for _, ip := range s {
		result = append(result, net.ParseIP(ip).To4())
	}
	return result
}

func addrs(s ...string) []netip.Addr {
	var result []netip.Addr
	for _, addr := range s {
		result = append(result, netip.MustParseAddr(addr))
	}
	return result
}

func servers(lifetime time.Duration, s ...string) *ndp.RecursiveDNSServer {
	return &ndp.RecursiveDNSServer{Lifetime: lifetime, Servers: addrs(s...)}
}

var testNow = time.Date(2026, 9, 16, 0, 0, 0, 0, time.UTC)

func TestResolvStateNameservers(t *testing.T) {
	now := testNow

	t.Run("v4 only", func(t *testing.T) {
		s := newResolvState()
		s.setLease("lan", ipv4s("192.168.1.1"))
		want := "# generated by gokrazy/dhcp\ndomain lan\nsearch lan\nnameserver 192.168.1.1\n"
		if got := string(render(s, now)); got != want {
			t.Errorf("render = %q, want %q", got, want)
		}
	})

	t.Run("v4 first, then v6, capped", func(t *testing.T) {
		s := newResolvState()
		s.updateRDNSS("eth0", servers(time.Hour, "2001:db8::1", "fe80::1"), now)
		s.setLease("", ipv4s("192.168.1.1", "192.168.1.2"))
		got := strings.Join(nameservers(render(s, now)), ",")
		if want := "192.168.1.1,192.168.1.2,2001:db8::1"; got != want {
			t.Errorf("nameservers = %s, want %s", got, want)
		}
	})

	t.Run("slot reserved for v6", func(t *testing.T) {
		s := newResolvState()
		s.setLease("", ipv4s("192.168.1.1", "192.168.1.2", "192.168.1.3"))
		s.updateRDNSS("eth0", servers(time.Hour, "2001:db8::1"), now)
		got := strings.Join(nameservers(render(s, now)), ",")
		if want := "192.168.1.1,192.168.1.2,2001:db8::1"; got != want {
			t.Errorf("nameservers = %s, want %s", got, want)
		}
	})

	t.Run("no slot reserved without v6", func(t *testing.T) {
		s := newResolvState()
		s.setLease("", ipv4s("192.168.1.1", "192.168.1.2", "192.168.1.3"))
		got := strings.Join(nameservers(render(s, now)), ",")
		if want := "192.168.1.1,192.168.1.2,192.168.1.3"; got != want {
			t.Errorf("nameservers = %s, want %s", got, want)
		}
	})

	t.Run("DHCP renewal does not clobber RDNSS", func(t *testing.T) {
		s := newResolvState()
		s.setLease("", ipv4s("192.168.1.1"))
		s.updateRDNSS("eth0", servers(time.Hour, "fe80::1"), now)
		s.setLease("", ipv4s("192.168.1.9"))
		got := strings.Join(nameservers(render(s, now)), ",")
		if want := "192.168.1.9,fe80::1%eth0"; got != want {
			t.Errorf("nameservers = %s, want %s", got, want)
		}
	})

	t.Run("refresh keeps order", func(t *testing.T) {
		s := newResolvState()
		s.updateRDNSS("eth0", servers(time.Hour, "2001:db8::1", "2001:db8::2"), now)
		s.updateRDNSS("eth0", servers(time.Hour, "2001:db8::2"), now.Add(time.Minute))
		got := strings.Join(nameservers(render(s, now)), ",")
		if want := "2001:db8::1,2001:db8::2"; got != want {
			t.Errorf("nameservers = %s, want %s", got, want)
		}
	})

	t.Run("lifetime", func(t *testing.T) {
		s := newResolvState()
		if !s.updateRDNSS("eth0", servers(time.Hour, "2001:db8::1"), now) {
			t.Errorf("new server: changed = false, want true")
		}
		if s.updateRDNSS("eth0", servers(time.Hour, "2001:db8::1"), now.Add(time.Minute)) {
			t.Errorf("lifetime refresh: changed = true, want false")
		}
		// Refreshed at now+1m, so still usable at now+1h.
		if got := nameservers(render(s, now.Add(time.Hour))); len(got) != 1 {
			t.Errorf("after refresh: nameservers = %v, want 1", got)
		}
		if got := nameservers(render(s, now.Add(2*time.Hour))); len(got) != 0 {
			t.Errorf("after expiry: nameservers = %v, want none", got)
		}
		if !s.updateRDNSS("eth0", servers(time.Hour, "2001:db8::1"), now.Add(2*time.Hour)) {
			t.Errorf("expired server re-advertised: changed = false, want true")
		}
		if !s.updateRDNSS("eth0", servers(0, "2001:db8::1"), now.Add(2*time.Hour)) {
			t.Errorf("withdrawal: changed = false, want true")
		}
		if got := nameservers(render(s, now.Add(2*time.Hour))); len(got) != 0 {
			t.Errorf("after withdrawal: nameservers = %v, want none", got)
		}
	})

	t.Run("unusable addresses", func(t *testing.T) {
		s := newResolvState()
		s.updateRDNSS("eth0", servers(time.Hour, "::ffff:192.0.2.1", "::", "::1", "ff02::1", "2001:db8::1"), now)
		got := strings.Join(nameservers(render(s, now)), ",")
		if want := "2001:db8::1"; got != want {
			t.Errorf("nameservers = %s, want %s", got, want)
		}
	})

	t.Run("infinite lifetime", func(t *testing.T) {
		s := newResolvState()
		s.updateRDNSS("eth0", servers(ndp.Infinity, "2001:db8::1"), now)
		if got := nameservers(render(s, now.AddDate(10, 0, 0))); len(got) != 1 {
			t.Errorf("nameservers = %v, want 1", got)
		}
	})
}

func TestWrite(t *testing.T) {
	now := testNow
	newState := func() (*resolvState, *[]string) {
		s := newResolvState()
		var written []string
		s.writeFile = func(contents []byte) error {
			written = append(written, string(contents))
			return nil
		}
		return s, &written
	}
	write := func(t *testing.T, s *resolvState, now time.Time) {
		t.Helper()
		if err := s.write(now); err != nil {
			t.Fatal(err)
		}
	}

	t.Run("not before the first lease", func(t *testing.T) {
		s, written := newState()
		s.updateRDNSS("eth0", servers(time.Hour, "2001:db8::1"), now)
		write(t, s, now)
		if len(*written) != 0 {
			t.Fatalf("written = %q, want nothing before the first lease", *written)
		}
		s.setLease("", ipv4s("192.168.1.1"))
		write(t, s, now)
		want := "# generated by gokrazy/dhcp\nnameserver 192.168.1.1\nnameserver 2001:db8::1\n"
		if len(*written) != 1 || (*written)[0] != want {
			t.Errorf("written = %q, want [%q]", *written, want)
		}
	})

	t.Run("prunes expired", func(t *testing.T) {
		s, written := newState()
		s.setLease("", ipv4s("192.168.1.1"))
		s.updateRDNSS("eth0", servers(time.Minute, "2001:db8::1"), now)
		write(t, s, now.Add(time.Minute))
		want := "# generated by gokrazy/dhcp\nnameserver 192.168.1.1\n"
		if len(*written) != 1 || (*written)[0] != want {
			t.Errorf("written = %q, want [%q]", *written, want)
		}
		s.mu.Lock()
		defer s.mu.Unlock()
		if len(s.v6) != 0 {
			t.Errorf("v6 = %v, want expired entries pruned", s.v6)
		}
	})

	t.Run("renewal without DNS servers", func(t *testing.T) {
		// Like before RDNSS support: the previous resolv.conf stays.
		s, written := newState()
		s.setLease("lan", ipv4s("192.168.1.1"))
		write(t, s, now)
		s.setLease("lan", nil)
		write(t, s, now)
		if len(*written) != 1 {
			t.Errorf("written = %q, want only the first resolv.conf", *written)
		}
	})

	t.Run("withdrawn RDNSS without DNS servers in the lease", func(t *testing.T) {
		s, written := newState()
		s.setLease("lan", nil)
		write(t, s, now)
		s.updateRDNSS("eth0", servers(time.Hour, "2001:db8::1"), now)
		write(t, s, now)
		s.updateRDNSS("eth0", servers(0, "2001:db8::1"), now)
		write(t, s, now)
		want := []string{
			"# generated by gokrazy/dhcp\ndomain lan\nsearch lan\nnameserver 2001:db8::1\n",
			"# generated by gokrazy/dhcp\ndomain lan\nsearch lan\n",
		}
		if !reflect.DeepEqual(*written, want) {
			t.Errorf("written = %q, want %q", *written, want)
		}
	})
}
